"""Round-trip-safe TSV read/write for the Zylbercweig data files.

**Why this exists.** The Zalmen app writes `core_db.tsv`, `org_alignment_review.tsv`
and `org_addresses_review.tsv` via `csv.DictWriter(f, delimiter="\\t")` with no
`lineterminator`, and csv's default is `\\r\\n`. So every shared data file on disk
is CRLF. A script that writes one back with Python's more natural-looking
`lineterminator="\\n"` rewrites **every line** of the file: a 3-row edit lands as
a 1290-line diff, which then collides with the app's auto-saves and has to be
untangled by hand.

That is not hypothetical — it happened on 2026-07-19 while reassigning three
Brooklyn orgs, and was caught only because `git diff --stat` said 1290/1290
instead of 3/3.

Use these helpers instead of raw `csv` for any file that something else also
writes:

    from tsv_io import read_tsv, write_tsv

    headers, rows = read_tsv(ADDRESSES)
    ...mutate rows...
    write_tsv(ADDRESSES, headers, rows)      # line endings preserved

`write_tsv` sniffs the existing file's terminator and keeps it, so it is
equally correct for the CRLF data files and the LF `*_punchlist.tsv` files
generated by the detect_* scripts. New files default to CRLF, matching what
the app would produce.
"""
from __future__ import annotations

import csv
from pathlib import Path
from typing import Iterable, Sequence

csv.field_size_limit(10**9)

_DEFAULT_TERMINATOR = "\r\n"  # what the Zalmen app's csv.DictWriter emits


def sniff_terminator(path: str | Path) -> str:
    """Return the line terminator `path` currently uses.

    Reads only the first line. Missing/empty file → the app's default, so a
    freshly-created file matches what the app would have written.
    """
    p = Path(path)
    if not p.exists() or p.stat().st_size == 0:
        return _DEFAULT_TERMINATOR
    with p.open("rb") as f:
        first = f.readline()
    if first.endswith(b"\r\n"):
        return "\r\n"
    if first.endswith(b"\n"):
        return "\n"
    return _DEFAULT_TERMINATOR


def read_tsv(path: str | Path) -> tuple[list[str], list[dict[str, str]]]:
    """(headers, rows). Opened with `newline=""` so csv — not the text layer —
    handles line endings; without it, embedded newlines inside quoted fields
    are silently mangled."""
    p = Path(path)
    with p.open(newline="", encoding="utf-8") as f:
        rd = csv.DictReader(f, delimiter="\t")
        return list(rd.fieldnames or []), list(rd)


def write_tsv(
    path: str | Path,
    headers: Sequence[str],
    rows: Iterable[dict[str, str]],
    *,
    terminator: str | None = None,
) -> None:
    """Write rows, preserving the file's existing line terminator by default.

    Pass `terminator` only to force one deliberately. `extrasaction="ignore"`
    is NOT used: a key absent from `headers` should surface as an error rather
    than silently dropping a column, which is how schema drift creeps in.
    """
    p = Path(path)
    term = terminator or sniff_terminator(p)
    with p.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(headers), delimiter="\t", lineterminator=term)
        w.writeheader()
        w.writerows(rows)


if __name__ == "__main__":
    # Self-check: round-tripping a real data file must be byte-identical.
    import hashlib
    import sys

    targets = [
        Path(__file__).parent / n
        for n in (
            "org_addresses_review.tsv",
            "core_db.tsv",
            "org_alignment_review.tsv",
        )
    ]
    bad = 0
    for t in targets:
        if not t.exists():
            print(f"skip (missing): {t.name}")
            continue
        before = hashlib.sha256(t.read_bytes()).hexdigest()
        headers, rows = read_tsv(t)
        tmp = t.with_suffix(".tsv.roundtrip_check")
        write_tsv(tmp, headers, rows)
        after = hashlib.sha256(tmp.read_bytes()).hexdigest()
        tmp.unlink()
        ok = before == after
        bad += not ok
        print(f"{'OK  ' if ok else 'FAIL'} {t.name:32} {sniff_terminator(t)!r:8} {len(rows)} rows")
    sys.exit(1 if bad else 0)
