"""Regenerate the Schema tab of docs/Visualizations/lateiner_hurwitz_entities.html.

The entity tree page is hand-maintained, but the schema it documents is not: it is
whatever build_entity_graph.py currently emits. So read data/entity_graph.json and
derive the schema from the data itself — node kinds and their fields, edge
relations with their endpoint kinds and attributes, the status and method
vocabularies, and the node-id conventions.

The script rewrites only the block between the SCHEMA markers in the page, so the
tree, the ledger and the surrounding prose are left untouched. Run it after every
build_entity_graph.py run; the page then reports the schema as built, not as
remembered.

    python3.11 -m build_schema_tab        # from YiDraCor/code/
"""
from __future__ import annotations

import html
import json
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent            # YiDraCor/
REPO = ROOT.parent                                       # Dybbuk/
GRAPH = ROOT / "data" / "entity_graph.json"
PAGE = REPO / "docs" / "Visualizations" / "lateiner_hurwitz_entities.html"

BEGIN = "<!-- SCHEMA:BEGIN (generated by code/build_schema_tab.py) -->"
END = "<!-- SCHEMA:END -->"

# Reading order: the spine of the graph first, then what hangs off it.
KIND_ORDER = ["person", "work", "edition", "song", "event", "org", "place"]

# What each kind is, in the project's own terms. Field semantics that a reader
# cannot guess from the name alone are spelled out; the rest are self-describing.
KIND_NOTE = {
    "person": "A real person — playwright, composer, actor, lyricist — resolved "
              "against people_db.",
    "work": "A play as the catalogue records it, keyed by its expression_id. The "
            "unit authorship attaches to; most works have no edition in this repo.",
    "edition": "A printed or manuscript witness in this repo: one built TEI, with "
               "its Transkribus document and folder.",
    "song": "A song in the song sheet, keyed to its play by play_key and hung off "
            "that work with part_of.",
    "event": "One dated performance from the performance-events report.",
    "org": "A company, troupe, publisher, theatre or holding library, resolved "
           "against core_db.",
    "place": "A settlement, resolved against the toponyms gazetteer (carries a "
             "Wikidata qid in db_id).",
}

FIELD_NOTE = {
    "id": "node id — kind-prefixed, see conventions below",
    "kind": "one of the seven kinds",
    "label": "display name, as the source writes it",
    "status": "LINKED or GAP (see vocabulary)",
    "method": "how the link was made (see vocabulary)",
    "merged_into": "on a duplicate record: the id it was merged into. The "
                   "surviving id is chosen on attribution evidence, not by "
                   "taking the lower number.",
    "db_id": "the id in the canonical database — people_db / core_db, or a "
             "Wikidata qid for places",
    "matched": "the database row's own spelling, for eyeballing the match",
    "reviewer": "who confirmed the link by hand; absent means automatic",
    "expression_id": "the catalogue's work key — the join between work and edition",
    "work_id": "the work this node hangs off",
    "play_key": "the song sheet's own play name, before resolution to a work_id",
    "link_status_to_work": "whether the play_key resolved to exactly one work",
    "attribution": "how firmly the authorship is asserted",
    "attribution_note": "the wording the catalogue uses for a qualified attribution",
    "counts": "source-catalogue row counts (productions, roles, songs, events) — "
              "not graph edges",
    "transkribus_doc_id": "Transkribus collection document id",
    "n_attestations": "how many sources attest the song",
    "author_certainty": "the song sheet's own confidence in the song's author",
    "extras": "catalogue columns carried through unparsed",
}

EDGE_NOTE = {
    "wrote": "authorship — attached to the work, not the edition, so works with "
             "no witness in this repo still carry their playwright",
    "realised_as": "the work this repo holds a witness of",
    "part_of": "the song belongs to this work",
    "of_work": "the performance event staged this work",
    "performed_at": "staged by or at this organisation",
    "premiered_in": "first staged in this place",
    "published": "this publisher issued the edition",
    "printed_in": "place of printing, from the imprint",
    "holds": "this library holds the witness (shelfmark on the edition)",
}

ATTR_NOTE = {
    "character": "the role credited",
    "context": "the source wording the credit came from",
    "level": "how direct the evidence is",
    "source": "which report or sheet the edge came from",
    "year": "year, where the source gives one",
    "date": "full date, where the source gives one",
    "type": "the performance-event type",
    "shelfmark": "the holding library's call number",
    "attribution": "how firmly the authorship is asserted",
}

STATUS_NOTE = {
    "LINKED": "an exact match on a normalised name or variant — carries a database id",
    "PROPOSED": "a high-confidence automatic candidate, not a decision; needs a "
                "human to confirm. None are currently outstanding.",
    "GAP": "no candidate, several equally good ones, or a match too weak to trust",
}

METHOD_NOTE = {
    "catalogue_expression_id": "minted from the catalogue's work key",
    "catalogue_song_sheet": "minted from a song-sheet row",
    "performance_events_report": "minted from the performance-events report",
    "reviewed": "a human confirmed it",
    "exact": "normalised name matched a database row outright",
    "composite-half": "matched one half of a core_db `A|B` composite name",
    "imprint-core": "matched after reducing the imprint to its core firm name",
    "exonym": "matched through a known alternative place name",
    "author_id": "taken from the catalogue's own author id",
    "qualifier-stripped": "matched after dropping a parenthetical qualifier",
}


def esc(s) -> str:
    return html.escape("" if s is None else str(s), quote=True)


def node_fields(nodes: list[dict]) -> dict[str, list[tuple[str, int, int]]]:
    """Per kind: each field, how many nodes carry it, and the kind's total."""
    order: dict[str, list[str]] = {}
    present: dict[str, Counter] = defaultdict(Counter)
    totals = Counter()
    for n in nodes:
        k = n.get("kind")
        totals[k] += 1
        seen = order.setdefault(k, [])
        for f in n:
            if f not in seen:
                seen.append(f)          # first-seen order reads better than sorted
            present[k][f] += 1
    return {
        k: [(f, present[k][f], totals[k]) for f in order[k]]
        for k in order
    }


def edge_shapes(nodes: list[dict], edges: list[dict]):
    """Per relation: endpoint kinds, count, and which attributes it carries."""
    kind = {n["id"]: n.get("kind") for n in nodes}
    counts = Counter()
    attrs: dict[tuple, Counter] = defaultdict(Counter)
    for e in edges:
        key = (e["rel"], kind.get(e["src"], "?"), kind.get(e["dst"], "?"))
        counts[key] += 1
        for f in e:
            if f not in ("src", "dst", "rel"):
                attrs[key][f] += 1
    rows = []
    for (rel, src, dst), n in counts.most_common():
        rows.append((rel, src, dst, n, [a for a, _ in attrs[(rel, src, dst)].most_common()]))
    return rows


def id_conventions(nodes: list[dict]) -> list[tuple[str, str]]:
    """One example id per kind, so the prefix scheme is visible rather than stated."""
    example: dict[str, str] = {}
    for n in nodes:
        example.setdefault(n.get("kind"), n.get("id"))
    return [(k, example[k]) for k in KIND_ORDER if k in example]


def render(graph: dict) -> str:
    nodes, edges = graph["nodes"], graph["edges"]
    summary = graph.get("summary", {})
    fields = node_fields(nodes)
    shapes = edge_shapes(nodes, edges)
    statuses = Counter(n.get("status") for n in nodes)
    methods = Counter(n.get("method") for n in nodes)

    kinds = [k for k in KIND_ORDER if k in fields]
    kinds += [k for k in fields if k not in kinds]      # anything new shows up too

    out = [BEGIN,
           '<section class="schema" id="pane-schema" role="tabpanel"'
           ' aria-labelledby="tab-schema" hidden>']

    out.append(
        '<p class="sec-note">The shape of <code>data/entity_graph.json</code> as '
        f'<code>build_entity_graph.py</code> currently builds it: '
        f'<b>{len(nodes)}</b> nodes across <b>{len(kinds)}</b> kinds and '
        f'<b>{len(edges)}</b> edges across <b>{len({r[0] for r in shapes})}</b> '
        'relations. Everything below is read off the graph itself, not kept by '
        'hand — regenerate with <code>build_schema_tab.py</code> after every '
        'graph build.</p>'
    )

    # ---- node kinds ----
    out.append("<h2>Node kinds</h2>")
    out.append('<div class="schema-kinds">')
    for k in kinds:
        rows = fields[k]
        total = rows[0][2] if rows else 0
        out.append('<details class="schema-kind" open><summary>'
                   f'<span class="caret">▸</span>'
                   f'<span class="schema-kind-name">{esc(k)}</span>'
                   f'<span class="dbid">{total} nodes · {len(rows)} fields</span>'
                   "</summary>")
        if KIND_NOTE.get(k):
            out.append(f'<p class="schema-note">{esc(KIND_NOTE[k])}</p>')
        out.append('<table class="schema-tbl"><thead><tr>'
                   "<th>field</th><th>on</th><th>meaning</th>"
                   "</tr></thead><tbody>")
        for f, present, tot in rows:
            cover = "all" if present == tot else f"{present}/{tot}"
            note = FIELD_NOTE.get(f, "")
            out.append(f"<tr><td><code>{esc(f)}</code></td>"
                       f'<td class="num">{esc(cover)}</td>'
                       f'<td class="meaning">{esc(note)}</td></tr>')
        out.append("</tbody></table></details>")
    out.append("</div>")

    # ---- edges ----
    out.append("<h2>Relations</h2>")
    out.append('<p class="sec-note">Every edge is '
               '<code>{src, dst, rel}</code> plus the attributes listed here. '
               'Read a row as <em>src kind → dst kind</em>.</p>')
    out.append('<div class="schema-scroll">')
    out.append('<table class="schema-tbl wide"><thead><tr>'
               "<th>relation</th><th>from → to</th><th>n</th>"
               "<th>attributes</th><th>meaning</th>"
               "</tr></thead><tbody>")
    for rel, src, dst, n, attrs in shapes:
        a = (" ".join(f"<code>{esc(x)}</code>" for x in attrs)
             if attrs else '<span class="ink3">—</span>')
        out.append(
            f"<tr><td><code>{esc(rel)}</code></td>"
            f'<td class="pair">{esc(src)} <span class="arrow">→</span> {esc(dst)}</td>'
            f'<td class="num">{n}</td><td>{a}</td>'
            f'<td class="meaning">{esc(EDGE_NOTE.get(rel, ""))}</td></tr>'
        )
    out.append("</tbody></table></div>")

    known_attrs = {a for r in shapes for a in r[4]}
    if known_attrs:
        out.append('<h3 class="schema-sub">Edge attributes</h3>')
        out.append('<table class="schema-tbl"><thead><tr>'
                   "<th>attribute</th><th>meaning</th>"
                   "</tr></thead><tbody>")
        for a in sorted(known_attrs):
            out.append(f"<tr><td><code>{esc(a)}</code></td>"
                       f'<td class="meaning">{esc(ATTR_NOTE.get(a, ""))}</td></tr>')
        out.append("</tbody></table>")

    # ---- vocabularies ----
    out.append("<h2>Vocabularies</h2>")
    out.append('<div class="schema-cols">')

    out.append('<div><h3 class="schema-sub">status</h3>'
               '<table class="schema-tbl"><thead><tr>'
               "<th>value</th><th>n</th><th>meaning</th>"
               "</tr></thead><tbody>")
    for v in ["LINKED", "PROPOSED", "GAP"]:
        n = statuses.get(v, 0)
        out.append(f"<tr><td><code>{esc(v)}</code></td>"
                   f'<td class="num">{n}</td>'
                   f'<td class="meaning">{esc(STATUS_NOTE[v])}</td></tr>')
    out.append("</tbody></table></div>")

    out.append('<div><h3 class="schema-sub">method</h3>'
               '<table class="schema-tbl"><thead><tr>'
               "<th>value</th><th>n</th><th>meaning</th>"
               "</tr></thead><tbody>")
    for v, n in methods.most_common():
        if not v:
            continue
        out.append(f"<tr><td><code>{esc(v)}</code></td>"
                   f'<td class="num">{n}</td>'
                   f'<td class="meaning">{esc(METHOD_NOTE.get(v, ""))}</td></tr>')
    out.append("</tbody></table></div>")
    out.append("</div>")

    # ---- id conventions ----
    out.append("<h2>Node id conventions</h2>")
    out.append('<p class="sec-note">Ids are <code>kind:slug</code>. A slug is a '
               'database id where the entity has one, the catalogue key where the '
               'catalogue supplies one, and a normalised name where neither does — '
               'so an id is stable only as far as its source is.</p>')
    out.append('<table class="schema-tbl"><thead><tr>'
               "<th>kind</th><th>example id</th>"
               "</tr></thead><tbody>")
    for k, eid in id_conventions(nodes):
        out.append(f"<tr><td>{esc(k)}</td><td><code>{esc(eid)}</code></td></tr>")
    out.append("</tbody></table>")

    # ---- open questions, from the graph's own tally ----
    gbr = summary.get("gaps_by_reason") or {}
    if gbr:
        out.append("<h2>What the graph still reports open</h2>")
        out.append('<p class="sec-note">'
                   f'{summary.get("gaps", len(graph.get("gaps", [])))} items, '
                   'grouped by the reason the builder recorded. These are missing '
                   'or ambiguous source data, not unidentified entities.</p>')
        out.append('<table class="schema-tbl"><thead><tr>'
                   "<th>n</th><th>reason</th></tr></thead><tbody>")
        for reason, n in sorted(gbr.items(), key=lambda x: -x[1]):
            out.append(f'<tr><td class="num">{n}</td>'
                       f'<td class="meaning">{esc(reason)}</td></tr>')
        out.append("</tbody></table>")

    out.append("</section>")
    out.append(END)
    return "\n".join(out)


def main() -> int:
    graph = json.loads(GRAPH.read_text(encoding="utf-8"))
    page = PAGE.read_text(encoding="utf-8")
    block = render(graph)

    if BEGIN not in page or END not in page:
        raise SystemExit(
            f"{PAGE.name} has no SCHEMA markers — add the tab shell first "
            "(see the repo history for this script's first run)."
        )
    head, rest = page.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    PAGE.write_text(head + block + tail, encoding="utf-8")

    n_rel = len({r[0] for r in edge_shapes(graph["nodes"], graph["edges"])})
    print(f"schema tab rebuilt: {len(graph['nodes'])} nodes, "
          f"{len(graph['edges'])} edges, {n_rel} relations → {PAGE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
